import { useLayoutEffect, useMemo, useRef, useState } from "react";
import ArrowUp from "../../assets/icons/ArrowUp";
import ArrowUpLink from "../../assets/icons/ArrowUpLink";
import CheckIcon from "../../assets/icons/CheckIcon";
import TrendDown from "../../assets/icons/TrendDown";
import TrendUp from "../../assets/icons/TrendUp";
import logoPdf from "../../assets/logo_PDF.png";
import { getPdfDetailSections } from "../../shared/utils/pdfDetailSections";
import {
  buildReportCitations,
  blockExtendsBelowFooter,
  blockExtendsBelowPatientLimit,
  buildPostSectionTitleVisibility,
  canPlaceInsightsOnPage1,
  consolidatePostOverviewSections,
  continuationPageHasContent,
  continuationPagesEqual,
  createEmptyContinuationPage,
  createInitialContinuationPage,
  getContinuationPageCitationStartIndex,
  getDeepDiveSections,
  getOverviewParagraphs,
  getPostOverviewSections,
  insightParagraphsEqual,
  mergeInsightParagraphs,
  paginateInsightParagraphs,
  parseCitationMeta,
  patientSectionFitsAfterAnchor,
  postOverviewSectionsEqual,
  postOverviewSectionsHasParagraph,
  prependPostOverviewParagraph,
  removeLastPostOverviewParagraph,
  shrinkCitationOnContinuationPage,
  shrinkDeepDiveOnContinuationPage,
  shrinkOverviewOnContinuationPage,
  shrinkPostOverviewOnContinuationPage,
  sourcesSectionOverflowsPage,
} from "./reportPrintUtils";
import styles from "./ReportPrintPage.module.css";

const pillClassByLevel = {
  Normal: styles.pillNormal,
  "Slightly Elevated": styles.pillSlightlyElevated,
  Elevated: styles.pillElevated,
  "Slightly Low": styles.pillSlightlyLow,
};

const pillIconByLevel = {
  Normal: CheckIcon,
  "Slightly Elevated": TrendUp,
  Elevated: ArrowUp,
  "Slightly Low": TrendDown,
};

const PhPillIcon = ({ level }) => {
  const Icon = pillIconByLevel[level] ?? CheckIcon;
  return <Icon className={styles.pillIcon} aria-hidden />;
};

const ReportPageShell = ({ children, timestamp, reportId, pageNum, totalPages }) => (
  <article className={styles.page} data-report-print>
    <header className={styles.header}>
      <img className={styles.logoHeader} src={logoPdf} alt="pHera" />
      <div className={styles.dateBlock}>
        <span className={styles.dateLine}>{timestamp}</span>
        <span className={styles.reportIdLine}>Report ID: {reportId}</span>
      </div>
    </header>

    <section className={styles.titleSection}>
      <h1 className={styles.reportTitle}>Vaginal pH Test Report</h1>
      <div className={styles.subBlock}>
        <p className={styles.subLine}>Generated by pHera</p>
        <p className={styles.subLine}>
          For personal use and sharing with a healthcare provider
        </p>
      </div>
    </section>
    <hr className={styles.divider} />

    <div className={styles.pageMain}>{children}</div>

    <footer className={styles.pageFooter}>
      <hr className={styles.footerDivider} data-footer-start />
      <p className={styles.disclaimer}>
        This report is generated by pHera for informational purposes only. It does
        not constitute medical advice or diagnosis. Please consult a qualified
        healthcare provider for any medical concerns
      </p>
      <div className={styles.footerRow}>
        <img className={styles.logoFooter} src={logoPdf} alt="" />
        <span className={styles.pageNum}>
          {pageNum}/{totalPages}
        </span>
      </div>
    </footer>
  </article>
);


const INSIGHT_INLINE_RE = /(\*\*[^*]+\*\*|\[[^\]]+\])/g;

/** Overview / Deep dive inline: **bold** labels and [n] citation refs. */
const InsightInline = ({ text }) => {
  const parts = String(text ?? "").split(INSIGHT_INLINE_RE).filter((part) => part !== "");

  return parts.map((part, index) => {
    const boldMatch = part.match(/^\*\*([^*]+)\*\*$/);
    if (boldMatch) {
      return <strong key={`${index}-b`}>{boldMatch[1]}</strong>;
    }
    if (/^\[[^\]]+\]$/.test(part)) {
      return (
        <span key={`${index}-r`} className={styles.bracketRef}>
          {part}
        </span>
      );
    }
    return <span key={`${index}-t`}>{part}</span>;
  });
};

const TextWithInsightInline = ({ text, className }) => (
  <p className={className}>
    <InsightInline text={text} />
  </p>
);

const DetailsTableCard = ({ title, rows, sectionKey }) => (
  <section
    className={styles.tableCard}
    data-flow-block
    {...(sectionKey ? { "data-section": sectionKey } : {})}
  >
    <h2 className={styles.tableTitle}>{title}</h2>
    <div className={styles.tableRows}>
      {rows.map((row) => (
        <div key={row.label} className={styles.tableRow}>
          <span className={styles.rowLabel}>{row.label}</span>
          <span className={styles.rowValue}>{row.value}</span>
        </div>
      ))}
    </div>
  </section>
);

const PatientDetailsSections = ({
  yourDetails,
  reportedSymptoms,
  showYourDetails,
  showSymptoms,
}) => (
  <>
    {showYourDetails && yourDetails.length > 0 ? (
      <DetailsTableCard title="Your details" rows={yourDetails} sectionKey="your-details" />
    ) : null}
    {showSymptoms && reportedSymptoms.length > 0 ? (
      <DetailsTableCard
        title="Reported symptoms"
        rows={reportedSymptoms}
        sectionKey="reported-symptoms"
      />
    ) : null}
  </>
);

const DeepDiveSection = ({ sections, showTitle = true }) => {
  if (!sections.length) return null;

  return (
    <section className={styles.deepDiveSection} data-flow-block data-deep-dive-section>
      {showTitle ? <h2 className={styles.insightsTitle}>Deep dive</h2> : null}
      <div className={styles.deepDiveCard}>
        {sections.map((section, index) => (
          <div key={`${section.title ?? "item"}-${index}`} className={styles.deepDiveSubsection}>
            <div className={styles.bulletRow}>
              <span className={`${styles.bullet} ${styles.bulletTeal}`} aria-hidden />
              <p className={styles.deepDiveItemText}>
                {section.title ? <strong>{section.title}</strong> : null}
                {section.title && section.body ? " " : null}
                {section.body ? <InsightInline text={section.body} /> : null}
              </p>
            </div>
          </div>
        ))}
      </div>
    </section>
  );
};

const OverviewItems = ({ paragraphs }) =>
  paragraphs.map((text, index) => (
    <div key={index} className={styles.overviewItem} data-insight-para>
      <span className={styles.bullet} aria-hidden />
      <TextWithInsightInline text={text} className={styles.bulletText} />
    </div>
  ));

const InsightBulletsSection = ({
  title,
  paragraphs,
  showTitle = true,
  isPostOverview = false,
}) => {
  if (!paragraphs.length) return null;

  return (
    <section
      className={styles.insightsSection}
      data-insights-section
      data-flow-block
      {...(isPostOverview ? { "data-post-overview-section": true } : {})}
    >
      {showTitle ? (
        <h2 className={styles.insightsTitle} data-insights-title>
          {title}
        </h2>
      ) : null}
      <div className={styles.insightsCardFull} data-insights-card>
        <OverviewItems paragraphs={paragraphs} />
      </div>
    </section>
  );
};

const PostOverviewSections = ({ sections, titleVisibility }) =>
  sections.map((section) => {
    if (!section.paragraphs.length) return null;
    const showTitle = titleVisibility?.get(section.key) ?? true;
    return (
      <InsightBulletsSection
        key={section.key}
        title={section.title}
        paragraphs={section.paragraphs}
        showTitle={showTitle}
        isPostOverview
      />
    );
  });

const CitationList = ({ citations, startIndex = 0 }) =>
  citations.map((citation, index) => {
    const meta = parseCitationMeta(citation);
    const num = startIndex + index + 1;
    return (
      <div key={`${num}-${meta.title}`} className={styles.citationRow} data-citation-row>
        <span className={styles.citationNum}>{num}.</span>
        <div className={styles.citationBody}>
          <p className={styles.citationTitle}>{meta.title}</p>
          {meta.detailText ? (
            <p className={styles.citationText}>{meta.detailText}</p>
          ) : null}
          {meta.links.length > 0 ? (
            <div className={styles.citationLinks}>
              {meta.links.map((link) => (
                <a
                  key={link.href}
                  className={styles.citationLink}
                  href={link.href}
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <span>{link.label}</span>
                  <ArrowUpLink className={styles.citationLinkIcon} aria-hidden />
                </a>
              ))}
            </div>
          ) : null}
        </div>
      </div>
    );
  });

const SourcesSection = ({
  citations,
  cardClassName,
  showHeading = true,
  startIndex = 0,
}) => {
  if (!citations.length) return null;
  return (
    <section className={styles.sourcesSection} data-flow-block data-sources-section>
      {showHeading ? (
        <h2 className={styles.insightsTitle}>Sources</h2>
      ) : null}
      <div className={cardClassName}>
        <CitationList citations={citations} startIndex={startIndex} />
      </div>
    </section>
  );
};

/**
 * Multi-page report body (same as /report-print, without toolbar).
 * @param {{ data: object, captureMode?: boolean, onLayoutReady?: () => void }} props
 */
const ReportPrintDocument = ({ data, captureMode = false, onLayoutReady }) => {
  const phValue = Number(data.phValue);
  const phLevel = data.phLevel ?? "Normal";
  const timestamp = data.timestamp ?? "";
  const interpretation = data.interpretation ?? "";
  const reportId = data.reportId ?? "PH-PREVIEW-DEV";

  const { yourDetails, reportedSymptoms } = getPdfDetailSections(data);
  const overviewParagraphs = useMemo(
    () => getOverviewParagraphs(data),
    [data?.overview]
  );
  const postOverviewSections = useMemo(
    () => getPostOverviewSections(data),
    [
      data?.your_ph,
      data?.your_symptoms,
      data?.your_personal_baseline,
      data?.your_health_context,
      data?.next_steps,
    ]
  );
  const deepDiveSections = useMemo(
    () => getDeepDiveSections(data),
    [data?.recommendations, data?.agent_reply]
  );
  const citations = useMemo(() => buildReportCitations(data), [data?.citations]);

  const page1Ref = useRef(null);
  const continuationPageRefs = useRef([]);
  const preInsightsProbeRef = useRef(null);
  const measureRef = useRef(null);
  const page1ShrinkGuardRef = useRef(0);
  const page1PostShrinkGuardRef = useRef(0);
  const continuationShrinkGuardRef = useRef(0);
  const postOverviewMigratedToPage2Ref = useRef(false);

  const [page1Overview, setPage1Overview] = useState([]);
  const [page1ShowYourDetails, setPage1ShowYourDetails] = useState(true);
  const [page1ShowSymptoms, setPage1ShowSymptoms] = useState(true);
  const [page1PostSections, setPage1PostSections] = useState([]);
  const [continuationPages, setContinuationPages] = useState(() => [
    createEmptyContinuationPage(),
  ]);

  const insightsOnPage1 = canPlaceInsightsOnPage1(
    reportedSymptoms,
    page1ShowSymptoms
  );

  const firstContinuationPage = continuationPages[0] ?? createEmptyContinuationPage();
  const postOverviewContinuesOnPage2 = firstContinuationPage.overviewParagraphs.length > 0;
  const hasPostOnPage1 = page1PostSections.some((section) => section.paragraphs.length > 0);

  const reportContentKey = useMemo(
    () =>
      [
        interpretation,
        phLevel,
        phValue,
        yourDetails.length,
        reportedSymptoms.length,
        overviewParagraphs.join("\x1e"),
        postOverviewSections
          .map((s) => `${s.key}\x1f${s.paragraphs.join("\x1e")}`)
          .join("\x1e"),
        deepDiveSections.map((s) => `${s.title ?? ""}\x1f${s.body}`).join("\x1e"),
        citations.length,
      ].join("\x1f"),
    [
      interpretation,
      phLevel,
      phValue,
      yourDetails.length,
      reportedSymptoms.length,
      overviewParagraphs,
      postOverviewSections,
      deepDiveSections,
      citations.length,
    ]
  );

  const showContinuationPages = continuationPages.some(continuationPageHasContent);
  const totalPages = 1 + (showContinuationPages ? continuationPages.length : 0);
  const firstOverviewContinuationIndex = continuationPages.findIndex(
    (page) => page.overviewParagraphs.length > 0
  );
  const firstDeepDiveContinuationIndex = continuationPages.findIndex(
    (page) => page.deepDive.length > 0
  );
  const firstSourcesContinuationIndex = continuationPages.findIndex(
    (page) => page.citations.length > 0
  );

  const postSectionTitleVisibility = useMemo(
    () =>
      buildPostSectionTitleVisibility([
        page1PostSections,
        ...continuationPages.map((page) => page.postSections),
      ]),
    [page1PostSections, continuationPages]
  );

  useLayoutEffect(() => {
    page1ShrinkGuardRef.current = 0;
    page1PostShrinkGuardRef.current = 0;
    continuationShrinkGuardRef.current = 0;
    postOverviewMigratedToPage2Ref.current = false;
    setPage1Overview((prev) => (prev.length === 0 ? prev : []));

    const showDetailsOnPage1 = yourDetails.length > 0;
    const showSymptomsOnPage1 = reportedSymptoms.length > 0;
    setPage1ShowYourDetails(showDetailsOnPage1);
    setPage1ShowSymptoms(showSymptomsOnPage1);

    const insightsStartOnPage2 = !canPlaceInsightsOnPage1(
      reportedSymptoms,
      showSymptomsOnPage1
    );

    if (insightsStartOnPage2) {
      setPage1PostSections([]);
    } else {
      setPage1PostSections((prev) =>
        postOverviewSectionsEqual(prev, postOverviewSections) ? prev : postOverviewSections
      );
    }

    const initialContinuation = createInitialContinuationPage({
      postOverviewSections,
      deepDiveSections,
      citations,
      insightsStartOnPage2,
      showYourDetails: insightsStartOnPage2 && showDetailsOnPage1,
      showSymptoms: insightsStartOnPage2 && showSymptomsOnPage1,
    });

    setContinuationPages((prev) =>
      continuationPagesEqual(prev, [initialContinuation]) ? prev : [initialContinuation]
    );
  }, [
    reportContentKey,
    yourDetails.length,
    reportedSymptoms.length,
    citations.length,
    postOverviewSections,
    deepDiveSections,
  ]);

  useLayoutEffect(() => {
    if (!postOverviewContinuesOnPage2) {
      postOverviewMigratedToPage2Ref.current = false;
      return;
    }
    if (!hasPostOnPage1 || postOverviewMigratedToPage2Ref.current) return;

    postOverviewMigratedToPage2Ref.current = true;
    setPage1PostSections((prev) => (prev.length === 0 ? prev : []));

    setContinuationPages((pages) => {
      const merged = consolidatePostOverviewSections(
        [page1PostSections, ...pages.map((page) => page.postSections)],
        postOverviewSections
      );
      const next = pages.map((page, index) =>
        index === 0
          ? { ...page, postSections: merged }
          : { ...page, postSections: [] }
      );
      return continuationPagesEqual(pages, next) ? pages : next;
    });
  }, [
    postOverviewContinuesOnPage2,
    hasPostOnPage1,
    postOverviewSections,
    page1PostSections,
    continuationPages,
  ]);

  useLayoutEffect(() => {
    const pageEl = page1Ref.current;
    const probeEl = preInsightsProbeRef.current;
    const measureSection = measureRef.current?.querySelector("[data-insights-measure]");
    if (!pageEl || !probeEl) return;

    const footerEl = pageEl.querySelector("[data-footer-start]");
    if (!footerEl) return;

    if (!canPlaceInsightsOnPage1(reportedSymptoms, page1ShowSymptoms)) {
      setPage1Overview((prev) => (prev.length === 0 ? prev : []));
      setContinuationPages((pages) => {
        const next = [...pages];
        next[0] = {
          ...next[0],
          overviewParagraphs: insightParagraphsEqual(
            next[0].overviewParagraphs,
            overviewParagraphs
          )
            ? next[0].overviewParagraphs
            : overviewParagraphs,
        };
        return continuationPagesEqual(pages, next) ? pages : next;
      });
      return;
    }

    const availablePx =
      footerEl.getBoundingClientRect().top - probeEl.getBoundingClientRect().bottom;

    const { page1, page2 } = paginateInsightParagraphs(
      availablePx,
      overviewParagraphs,
      measureSection
    );

    setPage1Overview((prev) => (insightParagraphsEqual(prev, page1) ? prev : page1));
    setContinuationPages((pages) => {
      const next = [...pages];
      next[0] = {
        ...next[0],
        overviewParagraphs: insightParagraphsEqual(next[0].overviewParagraphs, page2)
          ? next[0].overviewParagraphs
          : page2,
      };
      return continuationPagesEqual(pages, next) ? pages : next;
    });
  }, [
    interpretation,
    phLevel,
    phValue,
    yourDetails.length,
    reportedSymptoms.length,
    overviewParagraphs,
    page1ShowYourDetails,
    page1ShowSymptoms,
  ]);

  useLayoutEffect(() => {
    const pageEl = page1Ref.current;
    if (!pageEl) return;

    const probeEl = preInsightsProbeRef.current;
    const insightsEl = pageEl.querySelector("[data-insights-section]");
    const symptomsEl = pageEl.querySelector('[data-section="reported-symptoms"]');
    const detailsEl = pageEl.querySelector('[data-section="your-details"]');
    const interpretationEl = pageEl.querySelector("[data-page-content] [data-flow-block]");

    const insightsOverflow =
      page1Overview.length > 0 &&
      insightsEl &&
      blockExtendsBelowFooter(pageEl, insightsEl);
    const detailsOverflow =
      page1ShowYourDetails &&
      yourDetails.length > 0 &&
      detailsEl &&
      blockExtendsBelowPatientLimit(pageEl, detailsEl, probeEl);
    const symptomsOverflow =
      page1ShowSymptoms &&
      reportedSymptoms.length > 0 &&
      symptomsEl &&
      !patientSectionFitsAfterAnchor(
        detailsEl || interpretationEl,
        symptomsEl,
        probeEl,
        pageEl
      );

    if (!insightsOverflow && !symptomsOverflow && !detailsOverflow) {
      page1ShrinkGuardRef.current = 0;
      return;
    }

    if (page1ShrinkGuardRef.current > 40) return;
    page1ShrinkGuardRef.current += 1;

    if (insightsOverflow) {
      const removed = page1Overview[page1Overview.length - 1];
      setPage1Overview((prev) => {
        const next = prev.slice(0, -1);
        return insightParagraphsEqual(prev, next) ? prev : next;
      });
      setContinuationPages((pages) => {
        const next = [...pages];
        const first = next[0] ?? createEmptyContinuationPage();
        if (first.overviewParagraphs[0] === removed) return pages;
        next[0] = {
          ...first,
          overviewParagraphs: [removed, ...first.overviewParagraphs],
        };
        return continuationPagesEqual(pages, next) ? pages : next;
      });
      return;
    }

    if (detailsOverflow) {
      setPage1ShowYourDetails(false);
      setContinuationPages((pages) => {
        const next = [...pages];
        next[0] = { ...next[0], showYourDetails: true };
        return continuationPagesEqual(pages, next) ? pages : next;
      });
      return;
    }

    if (symptomsOverflow) {
      if (page1Overview.length > 0) {
        setContinuationPages((pages) => {
          const next = [...pages];
          const first = next[0] ?? createEmptyContinuationPage();
          next[0] = {
            ...first,
            overviewParagraphs: mergeInsightParagraphs(page1Overview, first.overviewParagraphs),
          };
          return continuationPagesEqual(pages, next) ? pages : next;
        });
        setPage1Overview([]);
      }
      setPage1ShowSymptoms(false);
      setContinuationPages((pages) => {
        const next = [...pages];
        next[0] = { ...next[0], showSymptoms: true };
        return continuationPagesEqual(pages, next) ? pages : next;
      });
      return;
    }
  }, [
    page1Overview,
    page1ShowYourDetails,
    page1ShowSymptoms,
    yourDetails.length,
    reportedSymptoms.length,
    interpretation,
    phLevel,
    phValue,
  ]);

  useLayoutEffect(() => {
    const pageEl = page1Ref.current;
    if (!pageEl || postOverviewContinuesOnPage2 || !hasPostOnPage1) return;

    const postNodes = pageEl.querySelectorAll("[data-post-overview-section]");
    const lastPostSection = postNodes[postNodes.length - 1];
    const postOverflow =
      lastPostSection && blockExtendsBelowFooter(pageEl, lastPostSection);

    if (!postOverflow) {
      page1PostShrinkGuardRef.current = 0;
      return;
    }

    if (page1PostShrinkGuardRef.current > 80) return;
    page1PostShrinkGuardRef.current += 1;

    const removed = removeLastPostOverviewParagraph(page1PostSections);
    if (!removed || postOverviewSectionsEqual(page1PostSections, removed.sections)) return;

    setPage1PostSections(removed.sections);

    setContinuationPages((pages) => {
      const first = pages[0] ?? createEmptyContinuationPage();
      if (postOverviewSectionsHasParagraph(first.postSections, removed.moved)) return pages;
      const next = [...pages];
      next[0] = {
        ...first,
        postSections: prependPostOverviewParagraph(first.postSections, removed.moved),
      };
      return continuationPagesEqual(pages, next) ? pages : next;
    });
  }, [
    page1PostSections,
    continuationPages,
    postOverviewContinuesOnPage2,
    hasPostOnPage1,
    page1Overview,
    page1ShowYourDetails,
    page1ShowSymptoms,
    interpretation,
    phLevel,
    phValue,
  ]);

  useLayoutEffect(() => {
    if (continuationShrinkGuardRef.current > 500) return;

    for (let pageIndex = 0; pageIndex < continuationPages.length; pageIndex += 1) {
      const pageEl = continuationPageRefs.current[pageIndex];
      if (!pageEl) continue;

      if (postOverviewContinuesOnPage2 && pageIndex === 0 && hasPostOnPage1) {
        continue;
      }

      const postNodes = pageEl.querySelectorAll("[data-post-overview-section]");
      const lastPostSection = postNodes[postNodes.length - 1];
      const postOverflow =
        lastPostSection && blockExtendsBelowFooter(pageEl, lastPostSection);

      if (postOverflow) {
        continuationShrinkGuardRef.current += 1;
        setContinuationPages((pages) => {
          const next = shrinkPostOverviewOnContinuationPage(pages, pageIndex);
          return next && !continuationPagesEqual(pages, next) ? next : pages;
        });
        return;
      }

      const insightsEl = pageEl.querySelector("[data-insights-section]");
      const overviewOverflow =
        continuationPages[pageIndex]?.overviewParagraphs.length > 0 &&
        insightsEl &&
        blockExtendsBelowFooter(pageEl, insightsEl);

      if (overviewOverflow) {
        continuationShrinkGuardRef.current += 1;
        setContinuationPages((pages) => {
          const next = shrinkOverviewOnContinuationPage(pages, pageIndex);
          return next && !continuationPagesEqual(pages, next) ? next : pages;
        });
        return;
      }

      const sourcesOverflow =
        continuationPages[pageIndex]?.citations.length > 0 &&
        sourcesSectionOverflowsPage(pageEl);

      if (sourcesOverflow) {
        continuationShrinkGuardRef.current += 1;
        setContinuationPages((pages) => {
          const next = shrinkCitationOnContinuationPage(pages, pageIndex);
          return next && !continuationPagesEqual(pages, next) ? next : pages;
        });
        return;
      }

      const deepDiveEl = pageEl.querySelector("[data-deep-dive-section]");
      const deepDiveOverflow =
        continuationPages[pageIndex]?.deepDive.length > 0 &&
        deepDiveEl &&
        blockExtendsBelowFooter(pageEl, deepDiveEl);

      if (deepDiveOverflow) {
        continuationShrinkGuardRef.current += 1;
        setContinuationPages((pages) => {
          const next = shrinkDeepDiveOnContinuationPage(pages, pageIndex);
          return next && !continuationPagesEqual(pages, next) ? next : pages;
        });
        return;
      }
    }

    continuationShrinkGuardRef.current = 0;
    setContinuationPages((pages) => {
      const compacted = pages.filter(continuationPageHasContent);
      if (compacted.length === 0 || continuationPagesEqual(pages, compacted)) return pages;
      return compacted;
    });
  }, [continuationPages, postOverviewContinuesOnPage2, hasPostOnPage1]);

  useLayoutEffect(() => {
    if (!onLayoutReady) return undefined;

    let cancelled = false;
    const timeoutId = window.setTimeout(() => {
      requestAnimationFrame(() => {
        requestAnimationFrame(() => {
          if (!cancelled) onLayoutReady();
        });
      });
    }, 0);

    return () => {
      cancelled = true;
      window.clearTimeout(timeoutId);
    };
  }, [
    onLayoutReady,
    page1Overview.length,
    page1ShowYourDetails,
    page1ShowSymptoms,
    page1PostSections.length,
    continuationPages,
    totalPages,
    interpretation,
    phLevel,
    phValue,
    yourDetails.length,
    reportedSymptoms.length,
    overviewParagraphs.length,
    postOverviewSections.length,
    deepDiveSections.length,
    citations.length,
  ]);

  const wrapClass = captureMode
    ? `${styles.exportRoot} ${styles.exportCapture}`
    : styles.documentPages;

  return (
    <div className={wrapClass}>
      <div className={styles.pageBreak}>
        <div ref={page1Ref} className={styles.page1Host}>
          <div ref={measureRef} className={styles.measureHost} aria-hidden>
            <section className={styles.insightsSection} data-insights-measure>
              <h2 className={styles.insightsTitle} data-insights-title>
                Your personalized insights
              </h2>
              <div className={styles.insightsCardFull} data-insights-card>
                <OverviewItems paragraphs={overviewParagraphs} />
              </div>
            </section>
          </div>

          <ReportPageShell
            timestamp={timestamp}
            reportId={reportId}
            pageNum={1}
            totalPages={totalPages}
          >
            <main className={styles.content} data-page-content>
              <section className={styles.resultCard} data-flow-block>
                <h2 className={styles.sectionTitle}>Interpretation</h2>
                <div className={styles.interpretationRow}>
                  <div className={styles.leftCol}>
                    <span
                      className={`${styles.pill} ${pillClassByLevel[phLevel] ?? styles.pillNormal}`}
                    >
                      <PhPillIcon level={phLevel} />
                      {phLevel}
                    </span>
                    <p className={styles.phValue}>{phValue.toFixed(1)}</p>
                    <p className={styles.phLabel}>pH value</p>
                  </div>
                  <p className={styles.interpCard}>{interpretation}</p>
                </div>
              </section>

              <PatientDetailsSections
                yourDetails={yourDetails}
                reportedSymptoms={reportedSymptoms}
                showYourDetails={page1ShowYourDetails}
                showSymptoms={page1ShowSymptoms}
              />

              <div
                ref={preInsightsProbeRef}
                className={styles.preInsightsProbe}
                data-pre-insights-probe
                aria-hidden
              />

              {insightsOnPage1 && page1Overview.length > 0 ? (
                <InsightBulletsSection title="Overview" paragraphs={page1Overview} />
              ) : null}

              {hasPostOnPage1 ? (
                <PostOverviewSections
                  sections={page1PostSections}
                  titleVisibility={postSectionTitleVisibility[0]}
                />
              ) : null}
            </main>
          </ReportPageShell>
        </div>
      </div>

      {showContinuationPages
        ? continuationPages.map((page, pageIndex) => {
            const pageNum = pageIndex + 2;
            const citationStartIndex = getContinuationPageCitationStartIndex(
              continuationPages,
              pageIndex
            );

            return (
              <div key={`continuation-${pageIndex}`} className={styles.pageBreak}>
                <div
                  ref={(node) => {
                    continuationPageRefs.current[pageIndex] = node;
                  }}
                >
                  <ReportPageShell
                    timestamp={timestamp}
                    reportId={reportId}
                    pageNum={pageNum}
                    totalPages={totalPages}
                  >
                    <main className={styles.content} data-page-content>
                      {pageIndex === 0 ? (
                        <PatientDetailsSections
                          yourDetails={yourDetails}
                          reportedSymptoms={reportedSymptoms}
                          showYourDetails={page.showYourDetails}
                          showSymptoms={page.showSymptoms}
                        />
                      ) : null}

                      {page.overviewParagraphs.length > 0 ? (
                        <InsightBulletsSection
                          title="Overview"
                          paragraphs={page.overviewParagraphs}
                          showTitle={
                            pageIndex === firstOverviewContinuationIndex &&
                            !(insightsOnPage1 && page1Overview.length > 0)
                          }
                        />
                      ) : null}

                      {page.postSections.some((section) => section.paragraphs.length > 0) ? (
                        <PostOverviewSections
                          sections={page.postSections}
                          titleVisibility={postSectionTitleVisibility[pageIndex + 1]}
                        />
                      ) : null}

                      {page.deepDive.length > 0 ? (
                        <DeepDiveSection
                          sections={page.deepDive}
                          showTitle={pageIndex === firstDeepDiveContinuationIndex}
                        />
                      ) : null}

                      {page.citations.length > 0 ? (
                        <SourcesSection
                          citations={page.citations}
                          cardClassName={styles.sourcesCardFull}
                          startIndex={citationStartIndex}
                          showHeading={pageIndex === firstSourcesContinuationIndex}
                        />
                      ) : null}
                    </main>
                  </ReportPageShell>
                </div>
              </div>
            );
          })
        : null}
    </div>
  );
};

export default ReportPrintDocument;
