import { useLayoutEffect, useMemo, useRef, useState } from "react";
import ArrowUp from "../../assets/icons/ArrowUp";
import ArrowUpLink from "../../assets/icons/ArrowUpLink";
import CheckIcon from "../../assets/icons/CheckIcon";
import TrendDown from "../../assets/icons/TrendDown";
import TrendUp from "../../assets/icons/TrendUp";
import logoPdf from "../../assets/logo_PDF.png";
import { getPdfDetailSections } from "../../shared/utils/pdfDetailSections";
import {
  buildReportCitations,
  deepDiveSectionsEqual,
  getDeepDiveSections,
  getOverviewParagraphs,
  blockExtendsBelowFooter,
  canPlaceInsightsOnPage1,
  insightParagraphsEqual,
  mergeInsightParagraphs,
  paginateInsightParagraphs,
  parseCitationMeta,
} from "./reportPrintUtils";
import styles from "./ReportPrintPage.module.css";

const pillClassByLevel = {
  Normal: styles.pillNormal,
  "Slightly Elevated": styles.pillSlightlyElevated,
  Elevated: styles.pillElevated,
  "Slightly Low": styles.pillSlightlyLow,
};

/** Same icons as PhBadge on ResultWithDetailsPage */
const pillIconByLevel = {
  Normal: CheckIcon,
  "Slightly Elevated": TrendUp,
  Elevated: ArrowUp,
  "Slightly Low": TrendDown,
};

const PhPillIcon = ({ level }) => {
  const Icon = pillIconByLevel[level] ?? CheckIcon;
  return <Icon className={styles.pillIcon} aria-hidden />;
};

const ReportPageShell = ({ children, timestamp, reportId, pageNum, totalPages }) => (
  <article className={styles.page} data-report-print>
    <header className={styles.header}>
      <img className={styles.logoHeader} src={logoPdf} alt="pHera" />
      <div className={styles.dateBlock}>
        <span className={styles.dateLine}>{timestamp}</span>
        <span className={styles.reportIdLine}>Report ID: {reportId}</span>
      </div>
    </header>

    <section className={styles.titleSection}>
      <h1 className={styles.reportTitle}>Vaginal pH Test Report</h1>
      <div className={styles.subBlock}>
        <p className={styles.subLine}>Generated by pHera</p>
        <p className={styles.subLine}>
          For personal use and sharing with a healthcare provider
        </p>
      </div>
    </section>
    <hr className={styles.divider} />

    <div className={styles.pageMain}>{children}</div>

    <footer className={styles.pageFooter}>
      <hr className={styles.footerDivider} data-footer-start />
      <p className={styles.disclaimer}>
        This report is generated by pHera for informational purposes only. It does
        not constitute medical advice or diagnosis. Please consult a qualified
        healthcare provider for any medical concerns
      </p>
      <div className={styles.footerRow}>
        <img className={styles.logoFooter} src={logoPdf} alt="" />
        <span className={styles.pageNum}>
          {pageNum}/{totalPages}
        </span>
      </div>
    </footer>
  </article>
);

const BRACKET_REF_RE = /(\[[^\]]+\])/g;

const BracketRefInline = ({ text }) => {
  const parts = String(text ?? "").split(BRACKET_REF_RE).filter((part) => part !== "");

  return parts.map((part, index) =>
    /^\[[^\]]+\]$/.test(part) ? (
      <span key={`${index}-${part}`} className={styles.bracketRef}>
        {part}
      </span>
    ) : (
      <span key={`${index}-t`}>{part}</span>
    )
  );
};

const TextWithBracketRefs = ({ text, className }) => (
  <p className={className}>
    <BracketRefInline text={text} />
  </p>
);

const BulletRow = ({ children, bulletClassName, textClassName }) => (
  <div className={styles.bulletRow}>
    <span className={`${styles.bullet} ${bulletClassName}`} aria-hidden />
    <p className={textClassName}>{children}</p>
  </div>
);

const DetailsTableCard = ({ title, rows }) => (
  <section className={styles.tableCard} data-flow-block>
    <h2 className={styles.tableTitle}>{title}</h2>
    <div className={styles.tableRows}>
      {rows.map((row) => (
        <div key={row.label} className={styles.tableRow}>
          <span className={styles.rowLabel}>{row.label}</span>
          <span className={styles.rowValue}>{row.value}</span>
        </div>
      ))}
    </div>
  </section>
);

/** Your details always before Reported symptoms */
const PatientDetailsSections = ({
  yourDetails,
  reportedSymptoms,
  showYourDetails,
  showSymptoms,
}) => (
  <>
    {showYourDetails && yourDetails.length > 0 ? (
      <DetailsTableCard title="Your details" rows={yourDetails} sectionKey="your-details" />
    ) : null}
    {showSymptoms && reportedSymptoms.length > 0 ? (
      <DetailsTableCard
        title="Reported symptoms"
        rows={reportedSymptoms}
        sectionKey="reported-symptoms"
      />
    ) : null}
  </>
);

const DeepDiveSection = ({ sections, showTitle = true }) => {
  if (!sections.length) return null;

  return (
    <section className={styles.deepDiveSection} data-flow-block data-deep-dive-section>
      {showTitle ? <h2 className={styles.insightsTitle}>Deep dive</h2> : null}
      <div className={styles.deepDiveCard}>
        {sections.map((section, index) => (
          <div key={`${section.title ?? "item"}-${index}`} className={styles.deepDiveSubsection}>
            <div className={styles.bulletRow}>
              <span className={`${styles.bullet} ${styles.bulletTeal}`} aria-hidden />
              <p className={styles.deepDiveItemText}>
                {section.title ? <strong>{section.title}</strong> : null}
                {section.title && section.body ? " " : null}
                {section.body ? <BracketRefInline text={section.body} /> : null}
              </p>
            </div>
          </div>
        ))}
      </div>
    </section>
  );
};

const OverviewItems = ({ paragraphs }) =>
  paragraphs.map((text, index) => (
    <div key={index} className={styles.overviewItem} data-insight-para>
      <span className={styles.bullet} aria-hidden />
      <TextWithBracketRefs text={text} className={styles.bulletText} />
    </div>
  ));

const TailoredInsightsSection = ({ overviewParagraphs, showTitle = true }) => {
  if (!overviewParagraphs.length) return null;

  return (
    <section className={styles.insightsSection} data-insights-section data-flow-block>
      {showTitle ? (
        <h2 className={styles.insightsTitle} data-insights-title>
          Overview
        </h2>
      ) : null}
      <div className={styles.insightsCardFull} data-insights-card>
        <OverviewItems paragraphs={overviewParagraphs} />
      </div>
    </section>
  );
};

const CitationList = ({ citations, startIndex = 0 }) =>
  citations.map((citation, index) => {
    const meta = parseCitationMeta(citation);
    const num = startIndex + index + 1;
    return (
      <div key={`${num}-${meta.title}`} className={styles.citationRow}>
        <span className={styles.citationNum}>{num}.</span>
        <div className={styles.citationBody}>
          <p className={styles.citationTitle}>{meta.title}</p>
          {meta.detailText ? (
            <p className={styles.citationText}>{meta.detailText}</p>
          ) : null}
          {meta.links.length > 0 ? (
            <div className={styles.citationLinks}>
              {meta.links.map((link) => (
                <a
                  key={link.href}
                  className={styles.citationLink}
                  href={link.href}
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <span>{link.label}</span>
                  <ArrowUpLink className={styles.citationLinkIcon} aria-hidden />
                </a>
              ))}
            </div>
          ) : null}
        </div>
      </div>
    );
  });

const SourcesSection = ({
  citations,
  cardClassName,
  showHeading = true,
  startIndex = 0,
}) => {
  if (!citations.length) return null;
  return (
    <section className={styles.sourcesSection} data-flow-block data-sources-section>
      {showHeading ? (
        <h2 className={styles.insightsTitle}>Sources</h2>
      ) : null}
      <div className={cardClassName}>
        <CitationList citations={citations} startIndex={startIndex} />
      </div>
    </section>
  );
};

/**
 * Three-page report body (same as /report-print, without toolbar).
 * @param {{ data: object, captureMode?: boolean, onLayoutReady?: () => void }} props
 */
const ReportPrintDocument = ({ data, captureMode = false, onLayoutReady }) => {
  const phValue = Number(data.phValue);
  const phLevel = data.phLevel ?? "Normal";
  const timestamp = data.timestamp ?? "";
  const interpretation = data.interpretation ?? "";
  const reportId = data.reportId ?? "PH-PREVIEW-DEV";

  const { yourDetails, reportedSymptoms } = getPdfDetailSections(data);
  const overviewParagraphs = useMemo(
    () => getOverviewParagraphs(data),
    [data?.overview]
  );
  const deepDiveSections = useMemo(
    () => getDeepDiveSections(data),
    [data?.recommendations, data?.agent_reply]
  );
  const citations = useMemo(() => buildReportCitations(data), [data?.citations]);

  const page1Ref = useRef(null);
  const page2Ref = useRef(null);
  const page3Ref = useRef(null);
  const preInsightsProbeRef = useRef(null);
  const measureRef = useRef(null);
  const page1ShrinkGuardRef = useRef(0);
  const page2ShrinkGuardRef = useRef(0);
  const page3ShrinkGuardRef = useRef(0);

  const [page1Overview, setPage1Overview] = useState([]);
  const [page2Overview, setPage2Overview] = useState([]);
  const [page1ShowYourDetails, setPage1ShowYourDetails] = useState(true);
  const [page1ShowSymptoms, setPage1ShowSymptoms] = useState(true);
  const [page2DeepDive, setPage2DeepDive] = useState([]);
  const [page3DeepDive, setPage3DeepDive] = useState([]);
  const [page2CitationCount, setPage2CitationCount] = useState(0);

  const insightsOnPage1 = canPlaceInsightsOnPage1(
    reportedSymptoms,
    page1ShowSymptoms
  );

  const page2InsightsParagraphs = useMemo(() => {
    if (!insightsOnPage1 && page1Overview.length > 0) {
      return mergeInsightParagraphs(page1Overview, page2Overview);
    }
    return page2Overview;
  }, [insightsOnPage1, page1Overview, page2Overview]);

  const reportContentKey = useMemo(
    () =>
      [
        interpretation,
        phLevel,
        phValue,
        yourDetails.length,
        reportedSymptoms.length,
        overviewParagraphs.join("\x1e"),
        deepDiveSections.map((s) => `${s.title ?? ""}\x1f${s.body}`).join("\x1e"),
        citations.length,
      ].join("\x1f"),
    [
      interpretation,
      phLevel,
      phValue,
      yourDetails.length,
      reportedSymptoms.length,
      overviewParagraphs,
      deepDiveSections,
      citations.length,
    ]
  );

  useLayoutEffect(() => {
    page1ShrinkGuardRef.current = 0;
    page2ShrinkGuardRef.current = 0;
    setPage1Overview((prev) => (prev.length === 0 ? prev : []));
    setPage2Overview((prev) => (prev.length === 0 ? prev : []));
    setPage1ShowYourDetails(yourDetails.length > 0);
    setPage1ShowSymptoms(reportedSymptoms.length > 0);
    setPage2DeepDive((prev) =>
      deepDiveSectionsEqual(prev, deepDiveSections) ? prev : deepDiveSections
    );
    setPage3DeepDive((prev) => (prev.length === 0 ? prev : []));
    setPage2CitationCount((prev) =>
      prev === citations.length ? prev : citations.length
    );
  }, [reportContentKey, yourDetails.length, reportedSymptoms.length, citations.length]);

  useLayoutEffect(() => {
    const pageEl = page1Ref.current;
    const probeEl = preInsightsProbeRef.current;
    const measureSection = measureRef.current?.querySelector("[data-insights-measure]");
    if (!pageEl || !probeEl) return;

    const footerEl = pageEl.querySelector("[data-footer-start]");
    if (!footerEl) return;

    if (!canPlaceInsightsOnPage1(reportedSymptoms, page1ShowSymptoms)) {
      setPage1Overview((prev) => (prev.length === 0 ? prev : []));
      setPage2Overview((prev) =>
        insightParagraphsEqual(prev, overviewParagraphs) ? prev : overviewParagraphs
      );
      return;
    }

    const availablePx =
      footerEl.getBoundingClientRect().top - probeEl.getBoundingClientRect().bottom;

    const { page1, page2 } = paginateInsightParagraphs(
      availablePx,
      overviewParagraphs,
      measureSection
    );

    setPage1Overview((prev) => (insightParagraphsEqual(prev, page1) ? prev : page1));
    setPage2Overview((prev) => (insightParagraphsEqual(prev, page2) ? prev : page2));
  }, [
    interpretation,
    phLevel,
    phValue,
    yourDetails.length,
    reportedSymptoms.length,
    overviewParagraphs,
    page1ShowYourDetails,
    page1ShowSymptoms,
  ]);

  useLayoutEffect(() => {
    const pageEl = page1Ref.current;
    if (!pageEl) return;

    const insightsEl = pageEl.querySelector("[data-insights-section]");
    const symptomsEl = pageEl.querySelector('[data-section="reported-symptoms"]');
    const detailsEl = pageEl.querySelector('[data-section="your-details"]');

    const insightsOverflow =
      page1Overview.length > 0 &&
      insightsEl &&
      blockExtendsBelowFooter(pageEl, insightsEl);
    const symptomsOverflow =
      page1ShowSymptoms &&
      reportedSymptoms.length > 0 &&
      symptomsEl &&
      blockExtendsBelowFooter(pageEl, symptomsEl);
    const detailsOverflow =
      page1ShowYourDetails &&
      yourDetails.length > 0 &&
      detailsEl &&
      blockExtendsBelowFooter(pageEl, detailsEl);

    if (!insightsOverflow && !symptomsOverflow && !detailsOverflow) {
      page1ShrinkGuardRef.current = 0;
      return;
    }

    if (page1ShrinkGuardRef.current > 40) return;
    page1ShrinkGuardRef.current += 1;

    if (insightsOverflow) {
      const removed = page1Overview[page1Overview.length - 1];
      setPage1Overview((prev) => {
        const next = prev.slice(0, -1);
        return insightParagraphsEqual(prev, next) ? prev : next;
      });
      setPage2Overview((prev) =>
        prev[0] === removed ? prev : [removed, ...prev]
      );
      return;
    }

    if (symptomsOverflow) {
      if (page1Overview.length > 0) {
        setPage2Overview((prev) => mergeInsightParagraphs(page1Overview, prev));
        setPage1Overview([]);
      }
      setPage1ShowSymptoms(false);
      return;
    }

    if (detailsOverflow) {
      setPage1ShowYourDetails(false);
    }
  }, [
    page1Overview,
    page2Overview,
    page1ShowYourDetails,
    page1ShowSymptoms,
    yourDetails.length,
    reportedSymptoms.length,
    interpretation,
    phLevel,
    phValue,
  ]);

  const deepDiveContinuesOnPage3 = page3DeepDive.length > 0;
  const serializeDeepDive = (sections) =>
    sections.map((s) => `${s.title ?? ""}\x1f${s.body}`).join("\x1e");
  const page2DeepDiveKey = serializeDeepDive(page2DeepDive);
  const page3DeepDiveKey = serializeDeepDive(page3DeepDive);
  const page2Citations = useMemo(
    () => citations.slice(0, page2CitationCount),
    [citations, page2CitationCount]
  );
  const page3Citations = useMemo(
    () => citations.slice(page2CitationCount),
    [citations, page2CitationCount]
  );
  const showSourcesOnPage2 = page2Citations.length > 0;
  const showPage3 = deepDiveContinuesOnPage3 || page3Citations.length > 0;
  const hasPage2OverflowDetails =
    (!page1ShowYourDetails && yourDetails.length > 0) ||
    (!page1ShowSymptoms && reportedSymptoms.length > 0);
  const showPage2Content =
    hasPage2OverflowDetails ||
    page2InsightsParagraphs.length > 0 ||
    page2DeepDive.length > 0 ||
    showSourcesOnPage2;
  const showPage2 = showPage2Content || showPage3;
  const totalPages = 1 + (showPage2 ? 1 : 0) + (showPage3 ? 1 : 0);

  useLayoutEffect(() => {
    const pageEl = page2Ref.current;
    if (!pageEl) return;

    const deepDiveEl = pageEl.querySelector("[data-deep-dive-section]");
    const sourcesEl = pageEl.querySelector("[data-sources-section]");
    const sourcesOverflow =
      page2Citations.length > 0 &&
      sourcesEl &&
      blockExtendsBelowFooter(pageEl, sourcesEl);
    const deepDiveOverflow =
      page2DeepDive.length > 0 &&
      deepDiveEl &&
      blockExtendsBelowFooter(pageEl, deepDiveEl);

    if (!sourcesOverflow && !deepDiveOverflow) {
      page2ShrinkGuardRef.current = 0;
      return;
    }

    if (page2ShrinkGuardRef.current > 40) return;
    page2ShrinkGuardRef.current += 1;

    if (sourcesOverflow && page2CitationCount > 0) {
      setPage2CitationCount((prev) => (prev > 0 ? prev - 1 : prev));
      return;
    }

    if (deepDiveOverflow && page2DeepDive.length > 0) {
      const removed = page2DeepDive[page2DeepDive.length - 1];
      setPage2DeepDive((prev) => {
        const next = prev.slice(0, -1);
        return deepDiveSectionsEqual(prev, next) ? prev : next;
      });
      setPage3DeepDive((prev) =>
        prev.length > 0 && prev[0] === removed ? prev : [removed, ...prev]
      );
    }
  }, [
    page2Overview.length,
    page2DeepDiveKey,
    page3DeepDiveKey,
    page2InsightsParagraphs.length,
    page1ShowYourDetails,
    page1ShowSymptoms,
    page2CitationCount,
    citations.length,
  ]);

  useLayoutEffect(() => {
    const pageEl = page3Ref.current;
    if (!pageEl || page3Citations.length === 0) {
      page3ShrinkGuardRef.current = 0;
      return;
    }

    const sourcesEl = pageEl.querySelector("[data-sources-section]");
    const sourcesOverflow =
      sourcesEl && blockExtendsBelowFooter(pageEl, sourcesEl);

    if (!sourcesOverflow) {
      page3ShrinkGuardRef.current = 0;
      return;
    }

    if (page3ShrinkGuardRef.current > 40) return;
    page3ShrinkGuardRef.current += 1;

    if (page2CitationCount < citations.length - 1) {
      setPage2CitationCount((prev) =>
        prev < citations.length - 1 ? prev + 1 : prev
      );
    }
  }, [
    page2CitationCount,
    page3Citations.length,
    citations.length,
    page3DeepDiveKey,
    deepDiveContinuesOnPage3,
  ]);

  useLayoutEffect(() => {
    if (!onLayoutReady) return undefined;

    let cancelled = false;
    const timeoutId = window.setTimeout(() => {
      requestAnimationFrame(() => {
        requestAnimationFrame(() => {
          if (!cancelled) onLayoutReady();
        });
      });
    }, 0);

    return () => {
      cancelled = true;
      window.clearTimeout(timeoutId);
    };
  }, [
    onLayoutReady,
    page1Overview.length,
    page2Overview.length,
    page2InsightsParagraphs.length,
    insightsOnPage1,
    page1ShowYourDetails,
    page1ShowSymptoms,
    page2DeepDiveKey,
    page3DeepDiveKey,
    interpretation,
    phLevel,
    phValue,
    yourDetails.length,
    reportedSymptoms.length,
    overviewParagraphs.length,
    deepDiveSections.length,
    citations.length,
    showSourcesOnPage2,
    showPage2,
    showPage3,
    totalPages,
    page2CitationCount,
    page3Citations.length,
  ]);

  const wrapClass = captureMode
    ? `${styles.exportRoot} ${styles.exportCapture}`
    : styles.documentPages;

  return (
    <div className={wrapClass}>
      <div className={styles.pageBreak}>
        <div ref={page1Ref} className={styles.page1Host}>
          <div ref={measureRef} className={styles.measureHost} aria-hidden>
            <section className={styles.insightsSection} data-insights-measure>
              <h2 className={styles.insightsTitle} data-insights-title>
                Your personalized insights
              </h2>
              <div className={styles.insightsCardFull} data-insights-card>
                <OverviewItems paragraphs={overviewParagraphs} />
              </div>
            </section>
          </div>

          <ReportPageShell
            timestamp={timestamp}
            reportId={reportId}
            pageNum={1}
            totalPages={totalPages}
          >
            <main className={styles.content} data-page-content>
              <section className={styles.resultCard} data-flow-block>
                <h2 className={styles.sectionTitle}>Interpretation</h2>
                <div className={styles.interpretationRow}>
                  <div className={styles.leftCol}>
                    <span
                      className={`${styles.pill} ${pillClassByLevel[phLevel] ?? styles.pillNormal}`}
                    >
                      <PhPillIcon level={phLevel} />
                      {phLevel}
                    </span>
                    <p className={styles.phValue}>{phValue.toFixed(1)}</p>
                    <p className={styles.phLabel}>pH value</p>
                  </div>
                  <p className={styles.interpCard}>{interpretation}</p>
                </div>
              </section>

              <PatientDetailsSections
                yourDetails={yourDetails}
                reportedSymptoms={reportedSymptoms}
                showYourDetails={page1ShowYourDetails}
                showSymptoms={page1ShowSymptoms}
              />

              <div
                ref={preInsightsProbeRef}
                className={styles.preInsightsProbe}
                aria-hidden
              />

              {insightsOnPage1 && page1Overview.length > 0 ? (
                <TailoredInsightsSection overviewParagraphs={page1Overview} />
              ) : null}
            </main>
          </ReportPageShell>
        </div>
      </div>

      {showPage2 ? (
        <div className={styles.pageBreak}>
          <div ref={page2Ref}>
            <ReportPageShell
              timestamp={timestamp}
              reportId={reportId}
              pageNum={2}
              totalPages={totalPages}
            >
              <main className={styles.content} data-page-content>
                <PatientDetailsSections
                  yourDetails={yourDetails}
                  reportedSymptoms={reportedSymptoms}
                  showYourDetails={!page1ShowYourDetails}
                  showSymptoms={!page1ShowSymptoms}
                />

                {page2InsightsParagraphs.length > 0 ? (
                  <TailoredInsightsSection
                    overviewParagraphs={page2InsightsParagraphs}
                    showTitle={!(insightsOnPage1 && page1Overview.length > 0)}
                  />
                ) : null}

                <DeepDiveSection
                  sections={page2DeepDive}
                  showTitle={page2DeepDive.length > 0}
                />

                {showSourcesOnPage2 ? (
                  <SourcesSection
                    citations={page2Citations}
                    cardClassName={styles.sourcesCardFull}
                    startIndex={0}
                  />
                ) : null}
              </main>
            </ReportPageShell>
          </div>
        </div>
      ) : null}

      {showPage3 ? (
        <div ref={page3Ref}>
          <ReportPageShell
            timestamp={timestamp}
            reportId={reportId}
            pageNum={3}
            totalPages={totalPages}
          >
            <main className={styles.content} data-page-content>
              {deepDiveContinuesOnPage3 ? (
                <DeepDiveSection
                  sections={page3DeepDive}
                  showTitle={page2DeepDive.length === 0 && page3DeepDive.length > 0}
                />
              ) : null}
              {page3Citations.length > 0 ? (
                <SourcesSection
                  citations={page3Citations}
                  cardClassName={styles.sourcesCardFull}
                  startIndex={page2CitationCount}
                  showHeading={page2CitationCount === 0}
                />
              ) : null}
            </main>
          </ReportPageShell>
        </div>
      ) : null}
    </div>
  );
};

export default ReportPrintDocument;
